openapi: 3.1.0
info:
  title: E-commerce API
  version: 1.0.0
servers:
  - url: http://localhost:3000/api
tags:
  - name: Users
    description: user-related endpoints
paths:
  /users:
    $ref: paths/users.yaml
  /users/{id}:
    $ref: paths/users_{id}.yaml
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
