openapi: 3.1.0
info:
  title: E-Commerce API
  version: 1.0.0
servers:
  - url: http://localhost:3000/api
tags:
  - name: Products
    description: Product-related endpoints
  - name: Orders
    description: Order-related endpoints
  - name: Categories
    description: category-related endpoints
  - name: Users
    description: user-related endpoints
paths:
  /products:
    $ref: './paths/products.yaml'
  /products/{id}:
    $ref: './paths/products{id}.yaml'
  /orders:
    $ref: './paths/orders.yaml'
  /orders/{id}:
    $ref: './paths/orders{id}.yaml'
    $ref: paths/products{id}.yaml
  /categories:
    $ref: paths/categories.yaml
  /categories/{id}:
    $ref: paths/categories{id}.yaml
  /users:
    $ref: paths/users.yaml
  /users/{id}:
    $ref: paths/users{id}.yaml
